export const ErrorCode = {
  IncorrectEmailPassword: "incorrect-email-password",
  UserNotFound: "user-not-found",
  IncorrectPassword: "incorrect-password",
  UserMissingPassword: "missing-password",
  TwoFactorDisabled: "two-factor-disabled",
  TwoFactorAlreadyEnabled: "two-factor-already-enabled",
  TwoFactorSetupRequired: "two-factor-setup-required",
  SecondFactorRequired: "second-factor-required",
  IncorrectTwoFactorCode: "incorrect-two-factor-code",
  InternalServerError: "internal-server-error",
  RateLimitExceeded: "rate-limit-exceeded",
  EmailNotVerified: "email-not-verified",
  EmailAlreadyExists: "email-already-exists",
  UsernameAlreadyExists: "username-already-exists",
  InvalidConfirmPassword: "invalid-confirm-password",
  InvalidRegisterPayload: "invalid-register-payload",
  ResetPasswordTokenNotFound: "reset-password-token-not-found",
  InvalidPasswordFormat: "invalid-password-format",
}
